rust_input: [src/api.rs]
dart_output: [../dart/lib/bridge_generated.dart]
wasm: true
dart_decl_output: ../dart/lib/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
c_output: [c_output_path/c_output.h]
extra_c_output_path:
  - c_output_path_extra/
symbol_prefix: "P343B03A6"
# dump: []
